// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOWANwG4-S9ZoSHIOb8ldI9YlmW1Fas8',
    appId: '1:660398834838:web:420dc98442ee7494292eb7',
    messagingSenderId: '660398834838',
    projectId: 'freeworkapp-4a056',
    authDomain: 'freeworkapp-4a056.firebaseapp.com',
    storageBucket: 'freeworkapp-4a056.appspot.com',
    measurementId: 'G-NK351YX9FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHM91URJLX34qOuOD5Uu2IEYNBkm2IBgc',
    appId: '1:660398834838:android:3bb9d14d41db4873292eb7',
    messagingSenderId: '660398834838',
    projectId: 'freeworkapp-4a056',
    storageBucket: 'freeworkapp-4a056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8PzS084dTZ9RqREhOwhV9-u7060ySWko',
    appId: '1:660398834838:ios:48ac013f965d3779292eb7',
    messagingSenderId: '660398834838',
    projectId: 'freeworkapp-4a056',
    storageBucket: 'freeworkapp-4a056.appspot.com',
    iosBundleId: 'com.example.freework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8PzS084dTZ9RqREhOwhV9-u7060ySWko',
    appId: '1:660398834838:ios:150d4be872b28d21292eb7',
    messagingSenderId: '660398834838',
    projectId: 'freeworkapp-4a056',
    storageBucket: 'freeworkapp-4a056.appspot.com',
    iosBundleId: 'com.example.freework.RunnerTests',
  );
}
